<?php
/*
session_start();
if(!isset($_SESSION["idusuario"]) || $_SESSION["idusuario"]==null){
	print "<script>alert(\"Acceso invalido!\");window.location='login.php';</script>";
}
*/
?>
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="./css/normalize.css" />
		<link rel="stylesheet" type="text/css" href="./css/demo.css" />
		<link rel="stylesheet" type="text/css" href="./css/component.css" />
		
		<link rel="stylesheet" href="css/bootstrap.min.css">

		
		<script src="./js/modernizr.custom.js"></script>
	

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	</head>

    <body>
		<?php include "views/navbarcam.phtml"; ?>	
        <div class="container">
		<header>	
			<h2>Ingreso Información Campo</h2>

                <form action="?action=<?php echo $cam->idcampo > 0 ? 'actualizar' : 'registrar'; ?>" method="post" class="pure-form pure-form-stacked" style="margin-bottom:30px;">
					<input type="hidden" name="idcampo" value="<?php echo $cam->__GET('idcampo'); ?>" />
                <table class="table table-dark">
				    <tr>
                        <th>codigo</th>
                        <td><input type="text" name="codigo" value="<?php echo $cam->__GET('codigo'); ?>" style="width:100%;" required/ ></td>
                    </tr>
					<tr>
                        <th>version</th>
                        <td><input type="text" name="version" value="<?php echo $cam->__GET('version'); ?>" style="width:100%;" required/ ></td>
                    </tr>
					<!--tr>
                        <th>fecha_emision</th>
                        <td><input type="text" name="fecha_emision" value="<?php echo $cam->__GET('fecha_emision'); ?>" style="width:100%;" required/ ></td>
                    </tr-->
					<tr>
                        <th>empleado_idempleado</th>
                        <td><input type="text" name="empleado_idempleado" value="<?php echo $cam->__GET('empleado_idempleado'); ?>" style="width:100%;" required/ ></td>
                    </tr>
					<tr>	
						<th colspan="2" style="text-align:left;"><button type="submit" class="btn btn-default">Guardar</button>

								<input align="right" type="button"  value="Regresar" class="btn btn-default" onclick="history.back()">
								
								<!--desa-->
								<input align="right" type="button"  value="Cancelar" class="btn btn-default" onclick=" location.href='http://localhost/hav/home.php' ">
								<!--prod-->
								<!--input align="right" type="button"  value="Cancelar" class="btn btn-default" onclick=" location.href='http://qtctsqlc01:8888/hav/' "-->
                         </th>
                     </tr>
                </table>

			</form>
		</header>
        </div>

    </body>
</html>