<?php
/*
session_start();
if(!isset($_SESSION["idusuario"]) || $_SESSION["idusuario"]==null){
	print "<script>alert(\"Acceso invalido!\");window.location='login.php';</script>";
}
*/
?>
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="./css/normalize.css" />
		<link rel="stylesheet" type="text/css" href="./css/demo.css" />
		<link rel="stylesheet" type="text/css" href="./css/component.css" />
		
		<link rel="stylesheet" href="css/bootstrap.min.css">

		
		<script src="./js/modernizr.custom.js"></script>
		
		<script language='JavaScript'>
			function enviaycierra(){
				if (confirm('Dar "Cancelar" si tiene campos en blanco, de lo contrario "Aceptar"')){
					document.form1.submit();
					alert("Se registró el empleado");
					window.opener.document.location.reload();
					window.close();
				}
			}
		</script>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	</head>

    <body>
		<?php include "views/navbarpopup.phtml"; ?>	
        <div class="container">
		<header>	
			<h2>Ingresar Nuevo Empleado</h2>

                <form name="form1" action="?action=<?php echo $eml->idempleado > 0 ? 'actualizar' : 'registrar'; ?>" method="post" class="pure-form pure-form-stacked" style="margin-bottom:30px;">
					<input type="hidden" name="idempleado" value="<?php echo $eml->__GET('idempleado'); ?>" />
                <table class="table table-dark">
				    <!--tr>
                        <th>empleado_numero</th>
                        <td><input type="text" name="empleado_numero" value="<?php echo $eml->__GET('empleado_numero'); ?>" style="width:100%;" required/ ></td>
                    </tr-->
					<tr>
                        <th>empleado_nombre</th>
                        <td><input type="text" name="empleado_nombre" value="<?php echo $eml->__GET('empleado_nombre'); ?>" style="width:100%;" required/ ></td>
                    </tr>
					<tr>
                        <th>empleado_dni</th>
                        <td><input type="text" name="empleado_dni" value="<?php echo $eml->__GET('empleado_dni'); ?>" style="width:100%;" ></td>
                    </tr>
					<tr>
                        <th>empleado_direccion</th>
                        <td><input type="text" name="empleado_direccion" value="<?php echo $eml->__GET('empleado_direccion'); ?>" style="width:100%;" ></td>
                    </tr>
					<tr>
                        <th>empleado_telefono</th>
                        <td><input type="text" name="empleado_telefono" value="<?php echo $eml->__GET('empleado_telefono'); ?>" style="width:100%;" required/ ></td>
                    </tr>
					<tr>
                        <th>empleado_email</th>
                        <td><input type="text" name="empleado_email" value="<?php echo $eml->__GET('empleado_email'); ?>" style="width:100%;" ></td>
                    </tr>
					<tr>	
						<th colspan="2" style="text-align:left;"><button type="submit" class="btn btn-default" onclick="javascript:enviaycierra();">Guardar</button>

								<!--input align="right" type="button"  value="Regresar" class="btn btn-default" onclick="history.back()"-->
								
								<!--desa-->
								<!--input align="right" type="button"  value="Cancelar" class="btn btn-default" onclick=" location.href='http://localhost/sasc' "-->
								<!--prod-->
								<input align="right" type="button"  value="Cancelar" class="btn btn-default" onclick="window.close();">
                         </th>
                     </tr>
                </table>

			</form>
		</header>
        </div>

    </body>
</html>