<?php
/*
session_start();
if(!isset($_SESSION["idusuario"]) || $_SESSION["idusuario"]==null){
	print "<script>alert(\"Acceso invalido!\");window.location='login.php';</script>";
}
*/
?>
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<link rel="shortcut icon" href="../favicon.ico">
		<link rel="stylesheet" type="text/css" href="./css/normalize.css" />
		<link rel="stylesheet" type="text/css" href="./css/demo.css" />
		<link rel="stylesheet" type="text/css" href="./css/component.css" />
		
		<link rel="stylesheet" href="css/bootstrap.min.css">

		
		<script src="./js/modernizr.custom.js"></script>


		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
		
		
		
	</head>

    <body>
		<?php include "views/navbarcom.phtml"; ?>	
        <div class="container">
		<header>	
			<h2>Ingresar Cotización</h2>

                <form action="?action=<?php echo $cot->idcotizacion > 0 ? 'actualizar' : 'registrar'; ?>" method="post" class="pure-form pure-form-stacked" style="margin-bottom:30px;">
					<input type="hidden" name="idcotizacion" value="<?php echo $cot->__GET('idcotizacion'); ?>" />
                <table class="table table-dark">
				    <tr>
						<th>empleado</th>
						<td>
                            <select name="empleado" style="width:100%;">
									<?php foreach($emp->Listar() as $e): ?>
									<option value="<?php echo $e->__GET('empleado_nombre'); ?>"><?php echo $e->__GET('empleado_nombre'); ?></option>
									<?php endforeach; ?>
                            </select>
						</td>
						<th><a href="new_empleado.php" onClick="window.open(this.href, this.target, 'width=600,height=600'); return false;" ><img src="./images/nuevo.png" /></a></th>
					</tr>
					<tr>
						<th>empresa</th>
						<td>
                            <select name="empresa" style="width:100%;">
									<?php foreach($em->Listar() as $p): ?>
									<option value="<?php echo $p->__GET('empresa_razon_social'); ?>"><?php echo $p->__GET('empresa_razon_social'); ?></option>
									<?php endforeach; ?>
                            </select>
						</td>
						<th><a href="new_empresa.php" onClick="window.open(this.href, this.target, 'width=600,height=600'); return false;" ><img src="./images/nuevo.png" /></a>
						</th>
					</tr>
					<tr>
                        <th>cotizacion_numero</th>
                        <td><input type="text" name="cotizacion_numero" value="<?php echo $cot->__GET('cotizacion_numero'); ?>" style="width:100%;" required/ ></td>
						<th></th>
                    </tr>
					<tr>
                        <th>cotizacion_descripcion</th>
						<td>
						<select name="cotizacion_descripcion" style="width:100%;">
							<option>Auditoria</option>
							<option>Capacitaciones</option>
							<option>Control Aviar</option>
							<option>Monitoreo Ocupacional</option>
							<option>Monitoreo Ambiental</option>
							<option>Residuos Sólidos</option>
							<option>Saneamiento</option>
							<option>SST</option>
							<option>Vigilancia Médica</option>
						</select>
						</td>
                        <th></th>
                    </tr>
					<!--tr>
                        <th>visita</th>
						<td>
						<select name="visita" style="width:100%;">
									<option>SI</option>
									<option>NO</option>
						</select>
						</td>
                        <th></th>
                    </tr-->
					<!--tr>
                        <th>sub_total</th>
                        <td><input type="text" name="sub_total" value="<?php echo $cot->__GET('sub_total'); ?>" style="width:100%;" required/ ></td>
						<th></th>
                    </tr-->					
					<!--tr>
                        <th>descripcion_cotizacion</th>
                        <td><input type="text" name="descripcion_cotizacion" value="<?php echo $cot->__GET('descripcion_cotizacion'); ?>" style="width:100%;" required/ ></td>
						<th></th>
                    </tr--->
					<!--tr>
                        <th>observacion_cotizacion</th>
                        <td><textarea name="observacion_cotizacion" value="<?php echo $cot->__GET('observacion_cotizacion'); ?>" rows="10" cols="40" style="width:100%;" required/ ></textarea></td>
						<th></th>
                    </tr-->
					<tr>	
						<th colspan="2" style="text-align:left;">

								<input align="right" type="button"  value="Regresar" class="btn btn-default" onclick="history.back()">
								<button type="submit" class="btn btn-default">Guardar</button>
								<!--desa-->
								<input align="right" type="button"  value="Cancelar" class="btn btn-default" onclick="location.href='index.php'">
								<!--prod-->
								<!--input align="right" type="button"  value="Cancelar" class="btn btn-default" onclick=" location.href='http://qtctsqlc01:8888/hav/' "-->
                         </th>
						 <th></th>
                     </tr>
                </table>

			</form>
		</header>
        </div>

    </body>
</html>