-- MySQL Script generated by MySQL Workbench
-- 10/24/19 20:35:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `empresa_numero` INT NULL,
  `empresa_razon_social` VARCHAR(100) NULL,
  `empresa_ruc` VARCHAR(11) NULL,
  `empresa_estado` VARCHAR(20) NULL,
  `empresa_direccion` VARCHAR(250) NULL,
  `empresa_telefono` VARCHAR(12) NULL,
  `empresa_contacto` VARCHAR(100) NULL,
  `empresa_correo` VARCHAR(100) NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `empleado_numero` INT NULL,
  `empleado_nombre` VARCHAR(100) NULL,
  `empleado_dni` VARCHAR(8) NULL,
  `empleado_direccion` VARCHAR(200) NULL,
  `empleado_telefono` VARCHAR(12) NULL,
  `empleado_estado` VARCHAR(20) NULL,
  `empleado_email` VARCHAR(100) NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cotizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cotizacion` (
  `idcotizacion` INT NOT NULL AUTO_INCREMENT,
  `cotizacion_numero` INT NULL,
  `cotizacion_fecha` DATETIME NULL,
  `cotizacion_descripcion` VARCHAR(255) NULL,
  `empresa_idempresa` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idcotizacion`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_cotizacion_empresa` ON `cotizacion` (`empresa_idempresa` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_cotizacion_empleado1` ON `cotizacion` (`empleado_idempleado` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `area` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `numero_area` INT NULL,
  `nombre_area` VARCHAR(45) NULL,
  `descripcion_area` VARCHAR(200) NULL,
  `estado_area` VARCHAR(1) NULL,
  PRIMARY KEY (`idarea`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `riesgo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `riesgo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `riesgo` (
  `idriesgo` INT NOT NULL AUTO_INCREMENT,
  `numero_riesgo` INT NULL,
  `tipo_riesgo` VARCHAR(100) NULL,
  `parametro_medicion` VARCHAR(200) NULL,
  `equipo_herramienta` VARCHAR(200) NULL,
  `metodo` VARCHAR(500) NULL,
  `costo_unitario` DECIMAL NULL,
  PRIMARY KEY (`idriesgo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `campo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `campo` (
  `idcampo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `fecha_emision` DATETIME NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idcampo`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_campo_empleado1` ON `campo` (`empleado_idempleado` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detalle_campo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalle_campo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detalle_campo` (
  `iddetalle_campo` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `numero_trabajador` INT NULL,
  `punto` INT NULL,
  `costo_parametro` DECIMAL NULL,
  `campo_idcampo` INT NOT NULL,
  `riesgo_idriesgo` INT NOT NULL,
  `area_idarea` INT NOT NULL,
  PRIMARY KEY (`iddetalle_campo`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_detalle_campo_campo1` ON `detalle_campo` (`campo_idcampo` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_detalle_campo_riesgo1` ON `detalle_campo` (`riesgo_idriesgo` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_detalle_campo_area1` ON `detalle_campo` (`area_idarea` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detalle_cotizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalle_cotizacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detalle_cotizacion` (
  `iddetalle_cotizacion` INT NOT NULL AUTO_INCREMENT,
  `detalle_cotizacion_version` VARCHAR(45) NULL,
  `detalle_cotizacion_monto` FLOAT(18,2) NULL,
  `detalle_cotizacion_comentario` VARCHAR(45) NULL,
  `detalle_cotizacion_fecha` DATETIME NULL,
  `detalle_cotizacion_visita` VARCHAR(45) NULL,
  `detalle_cotizacion_adjunto` VARCHAR(45) NULL,
  `detalle_cotizacion_pago` VARCHAR(45) NULL,
  `detalle_cotizacion_documento` VARCHAR(45) NULL,
  `detalle_cotizacion_condicion` VARCHAR(45) NULL,
  `detalle_cotizacion_gasto` FLOAT(18,2) NULL,
  `cotizacion_idcotizacion` INT NOT NULL,
  PRIMARY KEY (`iddetalle_cotizacion`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_detalle_cotizacion_cotizacion1_idx` ON `detalle_cotizacion` (`cotizacion_idcotizacion` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `manual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `manual` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `manual` (
  `id_manual` INT NOT NULL AUTO_INCREMENT,
  `autor` VARCHAR(45) NULL,
  `ruta` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `fecha_creacion` DATE NULL,
  `automatizado` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_manual`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
